### ISSUE TITLE
CUDA OOM due to model save for SHARDED_STATE_DICT

### ISSUE THREAD

**Issue by aditya-essential** [meta-llama/llama-recipes#55] opened 2023-07-26 22:14 UTC
My model training + eval runs fine for the epoch 0, then the model saves but epoch 1 fails due to OOM.

I am using FSDP (FULL_SHARD + SHARDED_STATE_DICT) w/o PEFT on p4de.24xlarge cluster. I verified that by removing the saving step the training proceeds just fine.

Also updated https://github.com/facebookresearch/llama-recipes/blob/main/model_checkpointing/checkpoint_handler.py#L67 to have ShardedStateDictConfig(offload_to_cpu=True) but the problem persists.

**Comment by aditya-essential** [comment] 2023-07-26 22:17
Epoch 0 (Train + Eval) - finishes successfully
Epoch 0 Model Save - finishes successfully

Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:21, 48.65s/it]
Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:21, 48.67s/it]
Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:20, 48.61s/it]
Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:21, 48.65s/it]
Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:21, 48.69s/it]
Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:20, 48.64s/it]
Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:20, 48.62s/it]
 step 0 is completed and loss is 0.16022688150405884

Training Epoch1:   7%|[34m▋         [0m| 1/15 [00:48<11:21, 48.66s/it]
Training Epoch1:   7%|[34m▋         [0m| 1/15 [01:14<17:29, 74.95s/it]

Traceback (most recent call last):
  File "/admin/ubuntu/sample-slurm-jobs/experimental/llama-recipes/llama_finetuning.py", line 239, in <module>
    fire.Fire(main)
  File "/admin/ubuntu/miniconda3/envs/pytorch-p310/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/admin/ubuntu/miniconda3/envs/pytorch-p310/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/admin/ubuntu/miniconda3/envs/pytorch-p310/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/admin/ubuntu/sample-slurm-jobs/experimental/llama-recipes/llama_finetuning.py", line 222, in main
    results = train(
  File "/admin/ubuntu/sample-slurm-jobs/experimental/llama-recipes/utils/train_utils.py", line 107, in train
    loss.backward()
  File "/admin/ubuntu/miniconda3/envs/pytorch-p310/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/admin/ubuntu/miniconda3/envs/pytorch-p310/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.54 GiB (GPU 0; 79.32 GiB total capacity; 46.85 GiB already allocated; 9.52 GiB free; 65.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by HamidShojanazeri** [comment] 2023-07-27 19:33
@aditya-essential can you pls share the command you are running? also would be helpful to confirm if you are on PT nightlies.

**Comment by aditya-essential** [comment] 2023-07-27 19:42
command: 
```torchrun --nnodes 1 --nproc_per_node 8  llama_finetuning.py --enable_fsdp --model_name "meta-llama/Llama-2-13b-hf" --dataset <my dataset name> --dist_checkpoint_root_folder /admin/ubuntu/sample-slurm-jobs/experimental/llama2 --output_dir /admin/ubuntu/sample-slurm-jobs/experimental/llama2 --dist_checkpoint_folder fine-tuned
```
I am using PT2.0.1

**Comment by chauhang** [comment] 2023-07-30 01:32
@aditya-essential Please try with the latest PyTorch nightlies and see if the issue is resolved

**Comment by aditya-essential** [comment] 2023-08-02 17:26
thanks @chauhang, will try with that.

**Comment by lwmlyy** [comment] 2023-08-17 08:09
@chauhang Hi，I lora-fintune Llama70b with the latest code and meet the same error when saving the ckpt. The pytorch version is latest nightly. The command is:
torchrun --nnodes 1 --nproc_per_node 8  llama_finetuning.py --enable_fsdp --low_cpu_fsdp --model_name ../Llama-2-70b-chat-hf --micro_batch_size 1 --batch_size_training 12 --dist_checkpoint_root_folder ../Llama-2-70b-chat-hf/ --dist_checkpoint_folder fine-tuned  --use_peft --peft_method lora --lr 2e-5  --pure_bf16

**Comment by HamidShojanazeri** [comment] 2024-05-07 00:21
It seems be solved, not able to repro it anymore, closing this pls feel free to re-open if still seeing the issue.

**Closed by HamidShojanazeri** 2024-05-07 00:21 UTC
Labels: question
