### ISSUE TITLE
No Model Saved when Training without FSDP or PEFT

### ISSUE THREAD

**Issue by jpmcd** [meta-llama/llama-recipes#221] opened 2023-09-22 22:25 UTC
### System Info

Python 3.9. Issue is with code in `utils.train_utils`.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

The `train` function in `utils.train_utils` does not currently have a way to save a model when not using PEFT or FSDP.

I use the default `train_config` in `configs/training.py` and I've added these keyword args at the top of `main` which update `train_config`:

```
    kwargs["run_validation"] = True
    kwargs["model_name"] = "/path/to/models/Llama-2-7b-hf"
    kwargs["quantization"] = True
    kwargs["batch_size_training"] = 16
    kwargs["val_batch_size"] = 16
    kwargs["num_workers_dataloader"] = 10
    kwargs["lr"] = 1e-5
```

For `enable_fsdp=False`, `train()` gets passed `fsdp_config=None` leading to errors at [here](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/utils/train_utils.py#L151).

A quick check can be added for `fsdp_config=None` but how should models be saved when not using either PEFT or FSDP?

The `save_model_checkpoint()` and `save_optimizer_checkpoint()` functions seem to rely on FSDP.

### Error logs

Model does not get saved when training without PEFT or FSDP.

### Expected behavior

Control flow to save models when not using PEFT or FSDP would be expected.

**Comment by HamidShojanazeri** [comment] 2023-09-26 15:00
@jpmcd thats is by design as we are providing only these two options, the reason is to train even 7b on single GPU without PEFT you will run into memory issues and going over 1 gpu, you would need a mechanism to shard your model which we use FSDP here. Can you pls share some numbers from your setting where you can achieve 1 gpu training without PEFT, that would help us to add the option.

**Comment by jpmcd** [comment] 2023-09-26 15:30
Sure, I'd be glad to share. I've actually been able to successfully run training on the 7b model without PEFT or FSDP, but with `quantization=True`, on our cluster's system which is comprised of mildly dated Xeon G6 CPUs + 2 V100 Voltas per node. Like you mention, I am only using one GPU for training. It isn't fast but it seems to work. Though I'll admit I've been reading into the specifics of quantization to see if there's something I'm misunderstanding about this.

What specifics would be helpful to share? E.g. device/memory specs, batch size, model length, and any particular observations like seconds per batch?

**Comment by HamidShojanazeri** [comment] 2023-10-22 19:29
I see, I think our assumption here for [checkpoint saving logic ](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/utils/train_utils.py#L141-L173)has been if someone use PEFT or FSDP. I am not sure if we would change that yet, but pls feel free to fix the logic here as it works for you.

**Comment by HamidShojanazeri** [comment] 2023-10-22 19:30
sorry didn't mean to close it.

**Comment by jpmcd** [comment] 2023-10-24 17:50
Okay, I'll give it a shot and see if it works on a large enough machine.

**Closed** 2024-08-19 17:40 UTC
Labels: triaged
